---
- import_tasks: raspi-facts.yml
- import_tasks: linux-facts.yml
- import_tasks: software.yml

- name: "set timezone"
  command: "timedatectl set-timezone {{ timezone }}"
  when: "timezone | default(false) and linux_tz != timezone"

- name: "set locale"
  command: "localectl set-locale LANG={{ locale }}"
  when: "locale|default(false) and linux_locale != locale"

- name: set wifi country
  command: "raspi-config nonint do_wifi_country {{ wifi_country }}"
  when: "wifi_country | default(false) and wifi_country != raspi_wifi_country"

- import_tasks: raspi-config.yml
