---
- name: get wifi country
  shell: "raspi-config nonint get_wifi_country || echo unknown"
  register: raspi_wifi_country
  changed_when: False
  check_mode: no
  tags:
    - raspi

- name: get SPI enabled status
  shell: "raspi-config nonint get_spi"
  register: raspi_spi_disabled
  changed_when: False
  check_mode: no
  tags:
    - raspi

- name: get I2C enabled status
  shell: "raspi-config nonint get_i2c"
  register: raspi_i2c_disabled
  changed_when: False
  check_mode: no
  tags:
    - raspi

- name: get I2C0 enabled status
  shell: "raspi-config nonint get_config_var dtparam=i2c_vc /boot/config.txt"
  register: raspi_i2c0_disabled
  changed_when: False
  check_mode: no
  tags:
    - raspi


- name: set raspi-config facts (all)
  set_fact:
    raspi_wifi_country: "{{ raspi_wifi_country.stdout }}"
    raspi_spi_enabled: "{{ raspi_spi_disabled.stdout == '0' }}"
    raspi_i2c_enabled: "{{ raspi_i2c_disabled.stdout == '0' }}"
    raspi_i2c0_enabled: "{{ raspi_i2c0_disabled.stdout == 'on' }}"
  check_mode: no
  tags:
    - raspi
