---
- name: enable/disable SPI
  command: "raspi-config nonint do_spi {{ 0 if enable_spi else 1 }}"
  when: "enable_spi | default(false) and enable_spi != raspi_spi_enabled"
  tags:
    - raspi

- name: enable/disable I2C
  command: "raspi-config nonint do_i2c {{ 0 if enable_i2c else 1 }}"
  when: "enable_i2c | default(false) and enable_i2c != raspi_i2c_enabled"
  tags:
    - raspi

- name: enable/disable I2C0
  command: "raspi-config nonint set_config_var dtparam=i2c_vc {% if enable_i2c %}on{% else %}off{% endif %} /boot/config.txt"
  when: "enable_i2c | default(false) and enable_i2c != raspi_i2c0_enabled"
  tags:
    - raspi
